import type { Investigation } from "./types";

// Build a shareable markdown "on-call report" from an investigation.
export function toMarkdown(inv: Investigation): string {
  const rc = inv.rootCause;
  const alts = inv.alternatives?.length
    ? `\n## Alternative hypotheses\n${inv.alternatives.map((a) => `- ${a}`).join("\n")}\n`
    : "";
  const test = inv.suggestedTest ? `\n## Suggested regression test\n${inv.suggestedTest}\n` : "";
  const tldr = rc.summary ? `\n> ${rc.summary}\n` : "";
  const detail = rc.details ? `\n## Technical detail\n${rc.details}\n` : "";
  return `# Incident Report — ${inv.problemId}
${tldr}
- **Root cause:** ${rc.what}
- **Location:** \`${rc.where.file}:${rc.where.line}\`
- **Why:** ${rc.why}
- **Impact:** ${rc.impact}
- **Confidence:** ${Math.round(inv.confidence * 100)}%
${detail}
## Proposed fix — \`${inv.proposedPatch.file}\`
${inv.proposedPatch.rationale}

\`\`\`diff
${inv.proposedPatch.unifiedDiff}
\`\`\`
${test}${alts}
_Generated by PatchPilot (Gemini + Dynatrace MCP)._`;
}

export function downloadMarkdown(filename: string, md: string) {
  const url = URL.createObjectURL(new Blob([md], { type: "text/markdown" }));
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
